# -*- coding: utf-8 -*-
"""Customer Personality Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MGVY1lTshLSh1zDs4-YoIwmGthEh4Hvw
"""

import pandas as pd

df = pd.read_csv("marketing_campaign.csv", sep='\t')

df.columns = [col.strip().lower().replace(" ", "_") for col in df.columns]

print("Missing values per column:")
print(df.isnull().sum())

df = df.drop_duplicates()

text_cols = df.select_dtypes(include='object').columns
for col in text_cols:
    df[col] = df[col].astype(str).str.strip().str.title()

if 'dt_customer' in df.columns:
    df['dt_customer'] = pd.to_datetime(df['dt_customer'], errors='coerce', dayfirst=True)

if 'year_birth' in df.columns:
    df['year_birth'] = pd.to_numeric(df['year_birth'], errors='coerce').astype('Int64')

df.to_csv("cleaned_marketing_campaign.csv", index=False)
print("✅ Cleaned dataset saved as 'cleaned_marketing_campaign.csv'")